from valueIteration.value_iteration_3D import value_iteration_3D
from valueIteration.value_iteration_4D import value_iteration_4D
from valueIteration.value_iteration_5D import value_iteration_5D
from valueIteration.value_iteration_6D import value_iteration_6D
