name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install libtinfo5 dependency
        run: sudo apt-get update && sudo apt-get install -y libtinfo5

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: ${{ env.odp }}
          auto-activate-base: false

      - name: Install optimized_dp package and dependencies
        shell: bash -l {0}
        run: |
          pip install -e .
          pip install pytest pytest-cov

      - name: Run tests
        shell: bash -l {0}
        run: pytest test/*.py -v